# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

# For local development

version: '2.1'
services:
  kibana:
    extends:
      file: docker-compose.services.yml
      service: kibana
  web:
    volumes:
      - .:/opt/inspire:ro
  worker:
    volumes:
      - .:/opt/inspire:ro
