# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

version: '2.1'
services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: inspirehep
    environment:
      - "INVENIO_DEBUG=True"
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:inspirehep@db:5432/inspirehep"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
      - "INVENIO_ENABLE_SECURE_HEADERS=False"
      - "INVENIO_INSPIRE_NEXT_URL=http://ui:8081"
      - "INVENIO_ENABLE_CORS=True"
  cache:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  db:
    image: postgres:9.6
    restart: "always"
    environment:
      - "POSTGRES_USER=inspirehep"
      - "POSTGRES_PASSWORD=inspirehep"
      - "POSTGRES_DB=inspirehep"
    ports:
      - "5432:5432"
  mq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
  es:
    build: ./docker/elasticsearch
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:5.6.4
    environment:
      - "ELASTICSEARCH_URL=http://es:9200"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports: ['5601:5601']
  flower:
    image: mher/flower
    command: --broker=amqp://guest:guest@mq:5672/ --broker_api=http://guest:guest@mq:15672/api/
    ports:
      - "5555:5555"

  inspire-next:
    image: "inspirehep/inspire-next:latest"
    environment:
      - "APP_DEBUG=True"
      - "APP_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:inspirehep@db:5432/inspirehep"
      - "APP_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "APP_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "APP_CACHE_REDIS_URL=redis://cache:6379/0"
      - "APP_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "APP_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "APP_ES_BULK_TIMEOUT=240"
      - "APP_DANGEROUSLY_ENABLE_LOCAL_LOGIN=True"
      - "APP_ENABLE_SECURE_HEADERS=False"
      - "APP_SECRET_KEY=CHANGE_ME"
