name: Pull request main (workflows)

on:
  pull_request_target:
    branches: [main]
    paths:
      - "workflows/**"
      - "docker-compose.yaml"
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  test:
    needs: lint
    uses: ./.github/workflows/test-workflows.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
