version: '2.1'

services:
  cypress:
    image: cypress/included:4.0.2
    volumes:
      - ./smoke-tests:/tests
    environment:
      - NODE_ENV=test
      - CI=${CI}
    entrypoint: [""]
    depends_on:
      - ui
  web:
    build:
      context: backend
      dockerfile: Dockerfile-local
  worker:
    build:
      context: backend
      dockerfile: Dockerfile-local
  ui-build:
    build:
      context: ui
      dockerfile: Dockerfile-build
    volumes:
      - ./ui:/usr/src/app
    command: /usr/src/app/build.sh
  record-editor-build:
    build:
      context: record-editor
      dockerfile: Dockerfile-build
    volumes:
      - ./record-editor:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "yarn && yarn build --delete-output-path=false"
