name: Backend unit test

on:
  push:
    branches: [master]
    paths: 
      - 'backend/**'
      - '.github/workflows/backend-unit.yml'
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-unit.yml'

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  Unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install system dependencies
        run: sudo apt-get install poppler-utils

      - name: Install poetry 1.0.0
        run: |
          wget https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
          python get-poetry.py --version 1.0.0
          echo "::add-path::$HOME/.poetry/bin"

      - name: Generate requirements
        working-directory: ./backend
        run: >
          poetry export
          --dev --without-hashes --format=requirements.txt
          >requirements.txt

      - name: Cache virtual env
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: inspirehep-backend-pip-${{ hashFiles('./backend/requirements.txt') }}

      - name: Install
        working-directory: ./backend
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Test
        working-directory: ./backend
        run: poetry run py.test tests/unit
