name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 6.9.1

      - name: lint
        run: npm run lint

      - name: write version
        run: node ./write-version.js

      - name: install
        run: |
          npm install buffer-shims
          export CHROME_BIN=chromium-browser
          export DISPLAY=:99.0
          npm install

      - name: build
        run: npm run build

      - name: build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: inspirehep/editor
          tag_with_ref: true

      - name: coverage
        run: npm run coveralls
