name: Pull request main (backoffice)

on:
  pull_request_target:
    branches: [main]
    paths:
      - 'backoffice-repo/backoffice/**'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
  test:
    needs: lint
    uses: ./.github/workflows/test-backoffice.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
